ToonYou:
  base: ""
  path: "models/StableDiffusion/clarity2Fp16.sapf.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [-1]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "cute young thin girl, legs spread, attacked by a horrifying creature, screaming, trendy rainbow hair"
    # - "cute young thin girl nude at the pool, trendy rainbow hair"

  n_prompt:
    - "bad,ugly,bad artist,blurry,low resolution"
    #- "badhandv4,easynegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3, bad-artist, bad_prompt_version2-neg"
