ToonYou:
  base: ""
  path: "models/StableDiffusion/flat2dAnimergeV3F16.vzgC.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "young 13 year old anime girl running through a neotokyo sakura street, lush nature, skyscrapers, path, trees, flowers"
    #- "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes,"
    #- "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern"
    #- "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle,"

  n_prompt:
    - "badhandv4,easynegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3, bad-artist, bad_prompt_version2-neg"
    #- ""
    #- ""
